[package]
name = "pr-review-r1"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/pr-review-r1.rs"
crate-type = ["cdylib"]

[dependencies]
regex = "1.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasmedge-bindgen = "0.4.0"
wasmedge-bindgen-macro = "0.4.0"
