[workspace]
members = [
    "github/slack/getting-started/rust",
    "github/slack/star-messager/rust",
    "github/slack/issue-notifier/rust",
    "github/slack/commit-syncer/rust",
    "github/slack/pr-messager/rust",

    "github/gmail/star-thanks-by-gmail/rust",
    "github/gmail/pr-thanks-by-gmail/rust",

    "github/sendgrid/star-thanks-by-sendgrid/rust",

    "github/notion/assign-notifier/rust",

    "github/twilio/star-messenger/rust",

    "github/github/pr-review-r0/rust",
    "github/github/pr-review-r1/rust",

    "slack/slack/calculator/rust",
    "slack/slack/reverse/rust",
    "slack/cloudinary/upload/rust",
    "cloudinary/slack/image-rotator/rust",
]
