[package]
name = "check-jira-id"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/check-jira-id.rs"
crate-type = ["cdylib"]

[dependencies]
flows-connector-dsi = { version = "0.1" }
regex = "1.6.0"
wasmedge-bindgen = "0.4.0"
wasmedge-bindgen-macro = "0.4.0"
